k9s:
  cluster: do-nyc3-ef-k8s-cluster
  namespace:
    active: default
    lockFavorites: false
    favorites:
      - default
      - buildkit
  view:
    active: apps/v1/deployments default
  featureGates:
    nodeShell: false
  proxy: null
