return {
  -- {
  --   "neovim/nvim-lspconfig",
  --   config = function()
  --     local lspconfig = require("lspconfig")
  --     local configs = require("lspconfig.configs")
  --
  --     -- Define expert LSP if not already defined
  --     if not configs.expert then
  --       configs.expert = {
  --         default_config = {
  --           cmd = { vim.fn.expand("~/.local/share/nvim/mason/packages/expert/expert_darwin_arm64") },
  --           filetypes = { "elixir", "eex", "heex", "surface" },
  --           root_dir = lspconfig.util.root_pattern("mix.exs", ".git"),
  --           settings = {},
  --         },
  --       }
  --     end
  --
  --     -- Setup expert LSP
  --     lspconfig.expert.setup({})
  --   end,
  -- },
  -- {
  --   "nvim-treesitter/nvim-treesitter",
  --   opts = {
  --     ensure_installed = {
  --       "elixir",
  --       "heex",
  --       "eex",
  --     },
  --   },
  -- },
}
